# App + Webserver with python and Flask
# on Ubuntu 14.04 LTS (Trusty Tahr)

FROM ubuntu
MAINTAINER Eugene Duboviy <eugene.dubovoy@gmail.com> | github.com/duboviy

# install python, pip, Flask, and pymongo
RUN apt-get update && apt-get install -y python-all python-pip git
RUN pip install Flask pymongo
